import Head from "next/head";
import styles from "../styles/Home.module.css";
import JobList from "../components/jobList/JobList";
import { JobType } from "../types/job-type";
import { FC } from "react";
import { fetchData } from "../utils";

type JobListProps = {
  data: JobType[];
};

const Home: FC<JobListProps> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <JobList jobs={data} />
      </main>
    </div>
  );
};
export async function getStaticProps() {
  const data = await fetchData();
  return { props: { data } };
}

export default Home;
